markdown: kramdown
exclude:
  - LICENSE
  - Makefile
  - README
markdown_ext: "md"

layouts: ./_noita
baseurl: /courses/Spring16/sta101.001
sakai: https://sakai.duke.edu/portal/site/22299c5a-2e30-49a7-b46d-289ae3e0d739
piazza: https://sakai.duke.edu/portal/site/22299c5a-2e30-49a7-b46d-289ae3e0d739/page/0e347ae9-a5b7-46d9-b4d3-fb81ec6562a0
sakai_ps: https://sakai.duke.edu/portal/site/22299c5a-2e30-49a7-b46d-289ae3e0d739/page/2d61ed96-8180-4c92-8afa-61b2c9ba5fc7
sakai_pa: https://sakai.duke.edu/portal/site/22299c5a-2e30-49a7-b46d-289ae3e0d739/page/ded8317e-62b3-43cf-a414-a7169219df88
videos: https://duke.coursera.org/duke-statistics-001/lecture
learn_obj: https://duke.coursera.org/duke-statistics-001/wiki
openintro: https://www.openintro.org/os
teams: https://docs.google.com/spreadsheets/d/1cQE2FdJC6jYIKEl6HqxSq9Ho6am1CXMmcL7hi2AXtfA/edit#gid=0

noita:
  name: Sta 101 - Data Analysis and Statistical Inference (Spring 2016)
  description: Sta 101 at Duke - taught by Dr. Cetinkaya-Rundel
  author:
    name: Mine Cetinkaya-Rundel
    url: http://stat.duke.edu/~mc301
    absolute: true
  lang: en
  topbar:
    toggle: Menu
    right:
      - name: Schedule
        url: /
      - name: Info
        url: /info/
      - name: Syllabus
        url: /syllabus/
      - name: Sakai
        url: https://sakai.duke.edu/portal/site/22299c5a-2e30-49a7-b46d-289ae3e0d739/page/f473d807-e64b-47bc-9a27-4e3ebb48496e
        absolute: true
      - name: RStudio
        url: https://vm-manage.oit.duke.edu/containers
        absolute: true
      - name: Links
        url: /links/
      - name: FAQ
        url: /faq/
